// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/dashboard-main/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-main">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-main/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-simple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-simple">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-simple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-repository/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-repository">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-repository/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bills">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/bills/search-simple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bills/search-simple">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/bills/search-simple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/bills/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bills/search">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/bills/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clients">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/legislators/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/legislators/crm">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/legislators/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/legislators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/legislators">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/legislators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/legislators/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/legislators/search">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/legislators/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-bills">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sources">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sync">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hello/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hello">> = Specific
  const handler = {} as typeof import("../../src/app/hello/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/test-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-simple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-simple">> = Specific
  const handler = {} as typeof import("../../src/app/test-simple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
